backend:
  name: git-gateway
  branch: master
  repo: dsabalete/gatsby_intro
media_folder: static/uploads
public_folder: /img
collections:
  - name: "meetups"
    label: "Meetup"
    folder: "src/meetups"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Meetup", name: "title", widget: "string", required: true}
      - { label: "Meetup date", name: "date", widget: "date" }
      - { label: "Meetup description", name: "description", widget: "markdown"  }
